### ISSUE TITLE
Doesn't work with most emails received from Thunderbird users

### ISSUE THREAD

**Issue by rostafiychuk** [jeevatkm/ReplyWithHeaderMozilla#8] opened 2016-01-28 16:21 UTC
Error: ReferenceError: assignment to undeclared variable eml
Source File: chrome://replywithheader/content/rwh.js
Line: 336

**Comment by jeevatkm** [comment] 2016-01-28 17:45
Thanks for reporting an issue. Can you please also share thunderbird version and OS details?

**Comment by rostafiychuk** [comment] 2016-01-29 09:29
Thunderbird 38.5.1
Linux Mint 17.3 (4.2.0-25-generic)

To reproduce this try to set:
Header 'From': Outlook Extended
Header 'To': Outlook
Header quoting: Outlook

I've changed "Header 'To'" to Default to avoid this issue.

**Comment by jeevatkm** [comment] 2016-01-31 18:48
Thanks for details, Once done I will let you know.

**Comment by jeevatkm** [comment] 2016-02-06 18:00
I don't have linux VM. I have tired in windows and Mac OS X. Not able to reproduce with above setting.

However, I have updated logic around it. Please give a try (http://docs.myjeeva.com/rwh-mozilla/replywithheader@myjeeva.com-v1.4-beta.xpi) and let me know.

If possible, help me with internal error info. Choose an email which caused an issue and keep a tap on debug window capture issue. Thanks.

Please follow below steps to gather error/debug info of RWH:

Enabling RWH Debug Mode:

1. Goto Thunderbird Preferences and click `Advanced Tab`
2. Click `Config Editor` button and continue with dialog
3. Type `extensions.replywithheader.debug` in the search text box
4. Double click `extensions.replywithheader.debug` row to enable. Now becomes true.

Gathering RWH Error/Debug info:

1. Press `Ctrl+Shit+J` to get debug Window
2. Goto your any email messages which has problem
3. Click on Reply/Reply All/Forward for those email messages
4. Now you will have error/debug info in the debug window which was brought by `Ctrl+Shit+J`

**Comment by rostafiychuk** [comment] 2016-02-07 21:44
@jeevatkm 
Thanks, now it works great.

I checked on Windows and it fails with 1.3 too. To reproduce this with old version you can try to send email to:
```
Jeevanandam M. <jeeva@myjeeva.com>, Jeevanandam M. <jeeva@myjeeva.com>
```

**Comment by jeevatkm** [comment] 2016-02-07 22:44
@rostafiychuk Thanks.  I'm glad it works in v1.4-beta. I will try to reproduce with v1.3 for my understanding.

**Comment by jeevatkm** [comment] 2016-02-11 19:41
@rostafiychuk I'm able to reproduce. Problem is for loop doesn't have `var or let` for variable at line # 336 in v1.3.

I'm closing this one. Please let me know, if you come across any issues or improvements.

**Closed by jeevatkm** 2016-02-11 19:41 UTC
Labels: bug
